### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by justin808** [chashnikov/IntelliJ-presentation-assistant#1]
Looks promising. I'm using in the RC of RubyMine 6 with Vim plugin.
1. Is it configurable? 
2. Where to report issues? 
3. Escape key sometimes does not function (I'm using vim bindings)
4. My keymap of ctrl-tab to go to next splitter does not work. 
5. How to turn off the display of keystrokes (menu choice to turn off does not disable the display of keystrokes.

**Comment by hadason** [comment]
+1 
I agree, it would be great if you can configure it to work only in Presentation mode. disabling the plugin requires restarting Webstorm at the moment which is quite annoying.
Beautiful plugin though :)

**Comment by chashnikov** [comment]
@hadason You don't need to disable the plugin to switch off its functionality, just use View | 'Descriptions of Action' menu item.

**Comment by MyDogTom** [comment]
Current plugin description even mention "Description of Action"
>This plugin shows name and Win/Mac shortcuts of any action you invoke (View | Descriptions of Actions)

but it's not obvious at all. I would make more obvious how enable/disable shortcuts display. Something like that:

>This plugin shows name and Win/Mac shortcuts of any action you invoke. Use  "View | Descriptions of Actions" to enable/disable shortcuts display.
