### ISSUE TITLE
Customize location of keystroke callouts

### ISSUE THREAD

**Issue by breandan** [chashnikov/IntelliJ-presentation-assistant#11]
Allow users to customize the position of keystroke callouts on the screen.

**Comment by chashnikov** [comment]
What positions do you want? At the left at the bottom, at the right at the bottom?

**Comment by AdyGould** [comment]
Whilst they may add noise, the ability to determine where they are shown is ideal for education purposes.

So placement options of nine positions: Top-Left, Top-Centre Top-Right, Middle-Left, Middle-Centre, Middle-Right, Bottom-Left, Bottom-Centre and Bottom-Right.

Also, the ability to change how the text within the "tips" are aligned (Left, Right, Centre) would be useful.

Finally, how about background/Foreground colours?

Ok, so I've added to breandan's original request, but hope that I've got my interpretation correct as to what he was looking for.
