### ISSUE TITLE
Callouts do not appear, even when in Presentation Mode

### ISSUE THREAD

**Issue by ewirch** [chashnikov/IntelliJ-presentation-assistant#15]
I'm using Presentation Assistant 0.9.9 and IntelliJ 2016.3 EAP (163.6110). Plugin looks configured correctly:
![image](https://cloud.githubusercontent.com/assets/1880345/19427115/0e69c9b4-9442-11e6-9857-21896ebd53a8.png)

Still, I don't see callouts for keyboard shortcuts in Presentation Mode. Tested: ALT-1, CTRL-SHIFT-A.

**Comment by ogoltsov** [comment]
I had this issue too, till i switch on 'Description of Actions' in 'View' menu.
<img width="273" alt="screen shot 2016-10-30 at 11 32 59 am" src="https://cloud.githubusercontent.com/assets/20884088/19834709/6642766a-9e95-11e6-9260-fd91cc42fd15.png">

**Comment by bora89** [comment]
Webstorm 2018.1.2 - no such a menu item out there

**Comment by chashnikov** [comment]
"Descriptions of Actions" is located in View | Appearance submenu in the recent IDE versions.
