### ISSUE TITLE
Add configuration for time and position

### ISSUE THREAD

**Issue by himerus** [chashnikov/IntelliJ-presentation-assistant#18]
Been using this for a while, and would love to see a configuration for customizing the amount of time the shortcut overlay displays (I'd like to shorten the time it is visible). 

In addition, a configuration (two fields) for an X/Y positioning of the displayed shortcut would be helpful as well.

**Comment by chashnikov** [comment]
Delay is now configurable. We have a separate issue about making position configurable (#11).
