### ISSUE TITLE
Does not work after IntelliJ upgrade to 2017.2

### ISSUE THREAD

**Issue by goostleek** [chashnikov/IntelliJ-presentation-assistant#19]
Version `0.9.10` of the plugin does not display shortcuts on performed keyboard actions anymore after upgrade to _IntelliJ IDEA 2017.2_.
  
#### Version information:

```
Build #IU-172.3317.76, built on July 15, 2017
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by chashnikov** [comment]
Are there any exceptions in idea.log (Help | Show Log)?

**Comment by goostleek** [comment]
No exceptions in logs. How can I contribute more? I can send any configuration/settings file if you want. Can I increase debug logging for the plugin somehow?

**Comment by goostleek** [comment]
Ok, I figured out the problem while I came [the comment](https://github.com/chashnikov/IntelliJ-presentation-assistant/issues/10#issuecomment-265871265). It seems that after the upgrade it became inactive or, more likely, I have disabled it accidentally by `Alt+Shift+d`.
