### ISSUE TITLE
Display of Icons under Linux Mint

### ISSUE THREAD

**Issue by huti26** [chashnikov/IntelliJ-presentation-assistant#21]
Hey,
on macos the presentation assistant replaces things like meta and comma with their icons. Is that possible on the linux version too? To clarify I add current result:

![myresult](https://user-images.githubusercontent.com/31436976/30537278-4fef8132-9c69-11e7-97a3-0919c05c143a.png)

And the wanted result:
![wantedresult](https://user-images.githubusercontent.com/31436976/30537284-53fcc15e-9c69-11e7-9cf2-285790291595.png)

Is this maybe totally unrelated to the presentation assistant and only a Issue of my operating system?

**Comment by chashnikov** [comment]
Do you want to show these symbols for your Linux keymap?

**Comment by huti26** [comment]
Yes

**Comment by chashnikov** [comment]
Why do you need to show Mac-specific symbols for Linux keymap?
Anyway there is a workaround: if the keymap name contains "Mac OS" substring it'll show Mac symbols in shortcuts.

**Comment by huti26** [comment]
Most of my friends use Macs, so its just more comfortable for them, when they see the symbols.
Also I am using the "Mac OS X 10.5+" keymap, but the workaround doesn't seem to work for me.

Tried duplicating the keymap and naming it "Mac OS" just to be sure, but that doesn't work either.

**Comment by huti26** [comment]
Its not an important feature at all, but I just wanted to add, that I tried out the workaround on windows 7 and 10 and it did not work either. I noticed while watching older tutorials, that the workaround did indeed work in the past though.
