### ISSUE TITLE
optionally disable notifications when using shortcuts

### ISSUE THREAD

**Issue by stefanhoelzl** [chashnikov/IntelliJ-presentation-assistant#26]
I am using this plugin to learn the shortcuts.
So if I am already using a shortcut I dont need the notification anymore.
Therefore it would be nice to optionally disable the notifications when shortcuts are used.

**Comment by chashnikov** [comment]
The plugin isn't supposed to be used for learning shortcuts. You can try using [Key Promoter X](https://plugins.jetbrains.com/plugin/9792-key-promoter-x) for that.
