### ISSUE TITLE
Unexisting menu item in descrption (View | Descriptions of Actions) 

### ISSUE THREAD

**Issue by turbanoff** [chashnikov/IntelliJ-presentation-assistant#28]
Plugin description contains reference to View | Descriptions of Actions:
>This plugin shows name and Win/Mac shortcuts of any action you invoke (View | Descriptions of Actions)

There is no `Descriptions of Actions` item in `View` menu.
![image](https://user-images.githubusercontent.com/741251/72189453-e508cd80-340d-11ea-878f-bbf9da9c413c.png)

How to enable plugin?

**Comment by chashnikov** [comment]
The menu item was moved to Appearance submenu in recent versions of IntelliJ IDEA, I'll update the description. BTW the option should be enabled by default when you install the plugin.

**Comment by chashnikov** [comment]
The plugin description was updated in 1.0.4.
