### ISSUE TITLE
Custom shorcuts not displayed

### ISSUE THREAD

**Issue by vnea** [chashnikov/IntelliJ-presentation-assistant#31]
Hello.

I have bind the custom shorcut **Main menu | Window | Editor Tabs | Split Vertically** to **ALT + V**.
When I use the shortcut, the **Split Vertically** text is correctly displayed but the shorcut **ALT + V** is not displayed.

I am using **IntelliJ IDEA Ultimate 2019.3.2** and **Presentation Assistant 1.0.3** on **Ubuntu 18.04**.

**Comment by chashnikov** [comment]
By default the plugin shows shortcut from the standard keymaps. If you want to show shortcuts from your own keymap, choose it in File | Settings | Appearance & Behavior | Presentation Assistant.

**Comment by vnea** [comment]
Oh perfect, it was the option **Default Copy**.

Thank you :)
