### ISSUE TITLE
Idea 2019.3 and 2019.2 crashes on Ubuntu 19.10 when this plugin is activated

### ISSUE THREAD

**Issue by joebew42** [chashnikov/IntelliJ-presentation-assistant#32]
Hello :wave: 

I am trying this plugin with these versions of Idea:

```
IntelliJ IDEA 2019.3.2 (Community Edition)
Build #IC-193.6015.39, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1915M
Cores: 12
Registry: 
Non-Bundled Plugins: 
```
and

```
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1915M
Cores: 12
Registry: 
Non-Bundled Plugins: 
```

For some reasons (apparantely I cannot see any errors from the console) when trying to move an Inner Class to a new package, the IDE suddenly crashes and with it also all the other applications opened.

Here an Example:

```
package com.company.myapp.somewhere;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class MyClassUnderTest {
    @Test
    public void i_am_a_test() throws Exception {
       new AnInnerClass();

        assertEquals(true, true);
    }

    private class AnInnerClass  {
    }
}
```
Here, just as an example, if I try to move the class `AnInnerClass` with `F6` and then I specify a new package for the destination, like: `com.company.myapp.nowhere`, the IDE just crash and also all other opened applications.

**Comment by chashnikov** [comment]
If IDE crashes there should be java_error_in_IDEA_*.log in the user home directory. Could you please attach it to the issue?

**Comment by chashnikov** [comment]
Cannot reproduce. Maybe the problem isn't related to the plugin at all.
