### ISSUE TITLE
Activate next window blocks the window to be activated when looping over windows.

### ISSUE THREAD

**Issue by extempl** [chashnikov/IntelliJ-presentation-assistant#33]
`Activate next window` blocks the window to be activated when looping over windows.

After the tooltip is hides - you can go to the next window, until the tooltip is shown again. Then it stuck.

It doesn't apply to the backward activation, though - there it doesn't block the flow.

**Comment by extempl** [comment]
Also, as related - tooltip `activate next/previous window` only shown on one of two opened projects (that's why it stuck on one and doesn't on another).

**Comment by chashnikov** [comment]
Duplicates #34.
