### ISSUE TITLE
`Command + ~` not working sometimes due to the plugin

### ISSUE THREAD

**Issue by dipengfei** [chashnikov/IntelliJ-presentation-assistant#34]
Hi Team,

Presentation Assistant is a cool and helpful plugin, but several users encounter the `Command + ~` not working issue on MacOS due to this plugin, for more details, please kindly check the issue in Jetbrains side,
https://youtrack.jetbrains.com/issue/IDEA-229319
Could you please kindly check it out?

Thank you in advance.!

**Comment by chashnikov** [comment]
It seems that the bug is in the platform code, see [this comment](https://youtrack.jetbrains.com/issue/IDEA-229319#focus=streamItem-27-3974062.0-0) for details.

**Comment by dipengfei** [comment]
Hi @chashnikov 
I saw such issue was fixed from IntelliJ side, please see the updates of this ticket,
https://youtrack.jetbrains.com/issue/IDEA-229319

Thank you!
