### ISSUE TITLE
Plugin doesn't work anymore

### ISSUE THREAD

**Issue by natiginfo** [chashnikov/IntelliJ-presentation-assistant#35]
After Android Studio 3.6 update, plugin stopped working. I tried reinstalling it, and it still doesn't work.

**Comment by chashnikov** [comment]
Are there any exceptions in idea.log (Help | Show Log)?

**Comment by natiginfo** [comment]
No, I couldn't find any exceptions in my current mac. I can try with another mac today and update issue

**Comment by chashnikov** [comment]
Also please check that the plugin is actually enabled (View | Appearance | Description of Actions toggle item is switched on).

**Comment by natiginfo** [comment]
After View -> Appearance -> Description of Actions, it started to work again as before. Not sure what AS 3.6 update changed that the plugin was disabled. 

Thanks for your help! 

I'll close the issue

**Comment by shalgrim** [comment]
This happens to me, too, where it just doesn't work anymore. I disabled and enabled the plugin and it still causes problems. My View > Appearance menu has no Description of Actions item in it
