### ISSUE TITLE
No macOS shortcuts on Linux

### ISSUE THREAD

**Issue by adostic** [chashnikov/IntelliJ-presentation-assistant#38]
After upgrade of Intellij IDEA Ultimate form 2019.3.3(193.6494.35) to version 2020.1(201.6668.121) there is no macOS in dropdown under Keymap in settings. 

2019.3.3(193.6494.35):
![tooltip2019](https://user-images.githubusercontent.com/2591466/79265667-c0057a00-7e96-11ea-8b5e-638998e10bba.png)
2020.1(201.6668.121):
![tooltip2020](https://user-images.githubusercontent.com/2591466/79266078-520d8280-7e97-11ea-888f-3e4b647fbf3a.png)

**Comment by chashnikov** [comment]
Non-default keymaps were extracted to plugins in IDEA 2020.1, try installing [macOS Keymap](https://plugins.jetbrains.com/plugin/13258-macos-keymap) plugin. Maybe we should add a link to it to the Settings.

**Comment by adostic** [comment]
Works like charm, I was not aware of this change.
It would be nice to have some info somewhere.

I will close issue, because it is not bug on this plugin.

Thanks for the help.
