### ISSUE TITLE
Windows keymap on MacOS displays with Mac keys

### ISSUE THREAD

**Issue by vesalvojdani** [chashnikov/IntelliJ-presentation-assistant#39]
I apologize if this is not a regression, but I vaguely recall this worked better in previous versions. If you try to display the Windows keymap on Mac OS, you get the windows shortcuts as you would type them on a Mac keyboard. So it shows the Mac key equivalents rather than "ctrl" and "alt". This can be quite confusing to windows users.

**Comment by chashnikov** [comment]
I've just uploaded version 1.0.6 which should fix the problem.

**Comment by pauleveritt** [comment]
Thanks very much @chashnikov for looking into this.

**Comment by phatboyg** [comment]
`Meta` instead of `Command` is annoying, seriously – can we get Command back since that's the key on Mac? Even Windows doesn't have a "meta" key...
