### ISSUE TITLE
Match The Aesthetics Of Current Theme

### ISSUE THREAD

**Issue by khalidabuhakmeh** [chashnikov/IntelliJ-presentation-assistant#40]
Allow users to specify the color scheme of the presentation pop-up or read styles from the current theme.

This is the current look and feel:

![image](https://user-images.githubusercontent.com/228256/83796824-9fc09300-a66f-11ea-93cb-6e5bcd6855de.png)

**Comment by chashnikov** [comment]
It's possible to configure colors in File | Settings | Editor | Color Scheme | Presentation Assistant.
