### ISSUE TITLE
Stopped working on 2021.3  and 2021.3.1?

### ISSUE THREAD

**Issue by victorrentea** [chashnikov/IntelliJ-presentation-assistant#52]
First of all, thanks for this amazing plugin!

I am a heavy user of it for my talks and presentations. But recently (several weeks-months) it stopped working.

Nothing in the "Event Log"

Below is the output of my IJ's "About" page.
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021
Licensed to Victor Rentea
Subscription is active until June 25, 2022.
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.9)
    CMD Support (1.0.5)
    Key Promoter X (2021.3)
    LimitedWIP (0.3.13)
    com.eclectide.intellij.whatthecommit (1.2)
    com.github.b3er.idea.plugins.arc.browser (0.23)
    com.intellij.plugins.emacskeymap (212.4535.15)
    com.intellij.plugins.macoskeymap (213.5744.3)
    com.jetbrains.edu (2021.12-2021.3-439)
    intellij-clock (2.0.0)
    manjaro.mpb (1.6)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    com.github.victorrentea.slf4jplugin (0.0.16)
    GrepConsole (12.2.211.6693.1)
    org.jetbrains.kotlin (213-1.6.10-release-944-IJ6461.79)
    hdzi.idea-editstarters-plugin (2.4.0)
    org.jetbrains.plugins.hocon (2021.1.0)
    org.sonarlint.idea (6.4.3.42541)
    com.intellij.plugins.html.instantEditing (213.5744.122)

Kotlin: 213-1.6.10-release-944-IJ6461.79

**Comment by chashnikov** [comment]
Do you see 'Descriptions of Actions' item in View | Appearance menu?

**Comment by victorrentea** [comment]
OMG!
I never knew about that flag! It works again!! My life is saved. 
Thank you enormously!
🍻

**Comment by chashnikov** [comment]
> I never knew about that flag! 

It's enabled by default btw. Maybe you had accidentally switched it off some time ago.

**Comment by victorrentea** [comment]
It's very likely as I use heavily various shortcuts to have pressed it by
accident.
Perhaps it could not have a keymap pre-bound to it? (I see it's now bound
to Alt-Shift-D)
[image: image.png]

Also, I tried reinstalling it with restarts in between, but probably the
setting OFF was persisted somewhere (it survived reinstall).

Thanks for such fast feedback!

Many of us owe you a big thank you!
Victor Rentea
Java Champion, Trainer & Consultant
(+4) 0720 019 564 <+40720019564>
victorrentea.ro <http://www.victorrentea.ro>
<https://ro.linkedin.com/in/victor-rentea-9339364a>
