### ISSUE TITLE
Second Shortcut not Showing when Used in Succession

### ISSUE THREAD

**Issue by OliverSieweke** [chashnikov/IntelliJ-presentation-assistant#54]
When a keyboard shortcut is used twice in a row, the second usage is not displayed (an empty pop up is seen instead.)

In the example below I use the `⌘D` shortcut twice to duplicate a row.
- It all works as expected on the first usage
- On the second usage the keyboard pop-up still shows but without any text.

https://user-images.githubusercontent.com/30631513/163578414-f3de2deb-3cfe-4c93-af60-d662ea7aaa57.mov

(*The pop up might be showing under the video controls*)

Environment:
- WebStorm `2022.1`
    - Presentation Assistant `1.0.9`
    - All non bundled plugins disabled
- macOS Montery `12.3.1`

**Comment by meiMingle** [comment]
I've encountered the same situation.

**Comment by helenjoscott** [comment]
+1 🙏  running into this with IntelliJ IDEA screencasts

**Comment by stefanscheidt** [comment]
I can confirm this on

IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1

**Comment by victorrentea** [comment]
+1 
One detail: if you allow the time for the popup to fadeout, the issues doesn't reproduce. It only happens when *the same* shortcut has to be displayed again while it's still visible.

**Comment by chashnikov** [comment]
Should be fixed in 1.0.10.

**Comment by victorrentea** [comment]
Yes, it's fixed on my machine. Thank you!
🍻
