### ISSUE TITLE
Feature: Please add enable / disable option

### ISSUE THREAD

**Issue by kedar-joshi** [chashnikov/IntelliJ-presentation-assistant#58]
As of now, plugin functionality can only be disabled by disabling the plugin entirely. During private development displaying key presses is not required. Having an option to enable / disable functionality would be convenient.

**Comment by chashnikov** [comment]
Actually, it can be enabled/disabled via the main menu: View | Appearance | Descriptions of Actions.

**Comment by kedar-joshi** [comment]
> Actually, it can be enabled/disabled via the main menu: View | Appearance | Descriptions of Actions.

Ah, thank you. That's exactly I was looking for.
