### ISSUE TITLE
Generate keystroke callouts for menu shortcuts

### ISSUE THREAD

**Issue by breandan** [chashnikov/IntelliJ-presentation-assistant#8]
Either display them by default or add an option to enable, for example: Alt+F, Alt+E, Alt+V.

**Comment by chashnikov** [comment]
Why do you need this? Callouts will be shown when you invoke a menu item, I think showing them when a submenu is displayed would just add noise.

**Comment by AdyGould** [comment]
Whilst they may add noise, the ability to determine where they are shown is ideal for education purposes.

So placement options of nine positions: Top-Left, Top-Centre Top-Right, Middle-Left, Middle-Centre, Middle-Right, Bottom-Left, Bottom-Centre and Bottom-Right.

Also, the ability to change how the text within the "tips" are aligned (Left, Right, Centre) would be useful.

Finally, how about background/Foreground colours?

Ok, so I've added to breandan's original request, but hope that I've got my interpretation correct as to what he was looking for.
